server:
  port: 1488
spring:
  application:
    name: reservation
  mvc:
    static-path-pattern: /resources/**
  profiles:
    active: local
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin